export const DEBOUNCE_WAIT_TIME = 50;
export const TH_MAX_WIDTH_PERCENTAGE_DESKTOP = 0.5;
export const TH_MAX_WIDTH_PERCENTAGE_MOBILE = 0.8;
const TH_RESIZABLE_MAX_WIDTH = Math.max(
    TH_MAX_WIDTH_PERCENTAGE_DESKTOP,
    TH_MAX_WIDTH_PERCENTAGE_MOBILE,
);
export {
    TH_RESIZABLE_MAX_WIDTH,
};
